---
title: "Funguild and Host"
author: "Alejandro Rojas"
date: "6/27/2018"
output: html_document
---

```{r libs, message=FALSE, warning=FALSE}
library(phyloseq)
library(dplyr)
library(tidyr)
library(tibble)
library(ggplot2)
library(vegan)
library(readr)
library(ampvis)

load(file = "SOB_files.rda")

#loading Colin's function to assign guild to a taxonomy file
#https://github.com/colinaverill/fg_assign.r
source("fg_assign.r")
```

```{r, echo=FALSE}
#Standardize abundances to the median sequencing depth
total <- median(sample_sums(SOB_data))
standf <- function(x, t=total) round(t * (x/sum(x)))
SOB_data.std <- transform_sample_counts(SOB_data, standf)
```


# Assigning guild to the taxonomy table

```{r, warning=FALSE}
str_charc <- function(x) { gsub('[f,p,c,o,k,g,s]__', '', x)}

test <- data.frame(tax_table(SOB_data)) %>% 
  dplyr::rename(kingdom = Kingdom, phylum = Phylum, class = Class, order = Order, family = Family, genus = Genus, species = Species) %>% rownames_to_column( var = "OTU_ID") %>%
  mutate_all(.funs = str_charc) %>%
  column_to_rownames("OTU_ID")


#test.clean <- data.frame(lapply(test, function(x) gsub('[f,p,c,o,k,g,s]__', '', x)))
                    
test.assign <- fg_assign(test)

```


```{r}

#Filtering Ecto using Funguild
ecto_OTU <- row.names(test.assign[grepl("Ecto", test.assign$guild),] )

ecto_SOB <- prune_taxa(ecto_OTU, SOB_data.std)


#alpha diversity
sample_data(ecto_SOB)$obs.physeq <- estimate_richness(ecto_SOB, measures = "Observed") 
head(sample_data((ecto_SOB)))

alpha_ectoSOB <- plot_richness(subset_samples(ecto_SOB, site_code != "null"),
                           x="state", 
                           measures = "Observed")

ggplot(data = sample_data(ecto_SOB), aes(x = state, y =obs.physeq)) +
  geom_boxplot(aes(fill = site_code)) + 
    scale_fill_discrete(labels = c("INV" = "Invasive", 
                              "PL" = "Plantation",
                              "UN" = "Native",
                              "null" = "Nullabor"),
                        name = "Site type") +
  xlab("Site") + ylab("Observed")
```

